version: '3.8'

services:
  cloudflare-analytics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudflare-analytics-display
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - analytics-internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production

networks:
  analytics-internal:
    driver: bridge

volumes:
  analytics_logs:
    external: false